// generated by zonemapdb@0.8.1 — do not edit
import { createClient, type Collection, type ClientOptions, type GenericClient } from "zonemapdb";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  products: Collection<Schema["products"], Records["products"]>;
}

const DEFAULT_BASE_PATH = "/zonemapdb";

export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
    ...opts,
  });
  return generic as unknown as Db;
}
