// generated by zonemapdb@0.8.1 — do not edit
export interface Movies {
  id: string;
  title: string;
  year: number;
  rating: number;
  director: string;
  genres: string[];
  overview: string;
}

export interface Records {
  movies: Movies;
}

export const schema = {
  movies: {
    fields: {
      id: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      title: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith", "contains"] },
      year: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"] },
      rating: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"], pruning: [] },
      director: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
      genres: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: ["equals", "in", "startsWith"], multi: true },
      overview: { kind: "string", operators: ["equals", "in", "startsWith", "endsWith", "contains", "not"], pruning: [] },
    },
  },
} as const;

export type Schema = typeof schema;
