import { describe, expect, test } from "vitest";
import { generateSchemaTs, generateClientTs } from "../src/codegen.js";
import type { Manifest } from "../src/types.js";

const manifest: Manifest = {
  formatVersion: 0,
  generatorVersion: "0.1.0",
  dataset: { collection: "movies", recordCount: 2, blockCount: 1, sortField: "year" },
  schema: {
    collection: "movies",
    sortField: "year",
    fields: {
      year: { kind: "number", isDate: false, indexed: true, operators: ["equals", "in", "gt", "gte", "lt", "lte"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"] },
      title: { kind: "string", isDate: false, indexed: false, operators: [], pruning: [] },
    },
  },
  blocks: [{ hash: "abc123", bytes: 10, count: 2 }],
  zonemap: { year: { splitPoints: [2000, 2005] } },
};

describe("generateSchemaTs", () => {
  const output = generateSchemaTs(manifest, "0.1.0");

  test("carries the generated-header stamp", () => {
    expect(output).toContain("generated by zonemapdb@0.1.0 — do not edit");
  });

  test("full record interface includes every declared field, indexed or not", () => {
    expect(output).toContain("export interface Movies {");
    expect(output).toMatch(/year:\s*number;/);
    expect(output).toMatch(/title:\s*string;/);
  });

  test("the schema const's fields map includes only queryable fields, each with what prunes", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toContain('year: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte"], pruning: ["equals", "in", "gt", "gte", "lt", "lte"] }');
    expect(schemaBlock).not.toMatch(/\btitle:/);
  });

  test("maps the collection into Records", () => {
    expect(output).toContain("export interface Records {\n  movies: Movies;\n}");
  });
});

describe("generateSchemaTs — multi/absent (T7)", () => {
  const t7Manifest: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      fields: {
        ...manifest.schema.fields,
        genres: { kind: "string", isDate: false, indexed: true, operators: ["equals", "in", "startsWith", "not"], pruning: ["equals", "in", "startsWith"], multi: true },
        tagline: { kind: "string", isDate: false, indexed: true, operators: ["equals", "in", "startsWith", "not"], pruning: ["equals", "in", "startsWith"], absent: true },
      },
    },
  };
  const output = generateSchemaTs(t7Manifest, "0.1.0");

  test("a multi field's record property is an array", () => {
    expect(output).toMatch(/genres:\s*string\[\];/);
  });

  test("an absent field's record property is optional", () => {
    expect(output).toMatch(/tagline\?:\s*string;/);
  });

  test("the schema const carries multi: true / absent: true only for the opted-in fields", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toContain("multi: true");
    expect(schemaBlock).toContain("absent: true");
    expect(schemaBlock).not.toMatch(/year:.*multi/);
    expect(schemaBlock).not.toMatch(/year:.*absent/);
  });
});

describe("generateSchemaTs — pk (T8)", () => {
  const pkManifest: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      pk: "year",
      fields: { ...manifest.schema.fields, year: { ...manifest.schema.fields.year!, pk: true } },
    },
  };
  const output = generateSchemaTs(pkManifest, "0.1.0");

  test("the schema const carries a collection-level pk naming the field", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toMatch(/pk:\s*"year"/);
  });

  test("the pk field's own entry carries pk: true; other fields omit it", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).toMatch(/year:\s*\{[^}]*pk:\s*true/);
  });

  test("no pk configured omits the collection-level pk key entirely", () => {
    const noPkOutput = generateSchemaTs(manifest, "0.1.0");
    const schemaBlock = noPkOutput.slice(noPkOutput.indexOf("export const schema"));
    expect(schemaBlock).not.toMatch(/\bpk:/);
  });
});

describe("generateClientTs", () => {
  const output = generateClientTs(manifest, { basePath: "/zonemapdb", generatorVersion: "0.1.0" });

  test("carries the generated-header stamp", () => {
    expect(output).toContain("generated by zonemapdb@0.1.0 — do not edit");
  });

  test("imports the generic runtime and the sibling schema module", () => {
    expect(output).toContain('from "zonemapdb"');
    expect(output).toContain('from "./schema.js"');
  });

  test("declares a named Db member for the collection", () => {
    expect(output).toContain("movies: Collection<Schema[\"movies\"], Records[\"movies\"]>");
  });

  test("bakes the configured basePath as connect()'s default", () => {
    expect(output).toContain('"/zonemapdb"');
    expect(output).toContain("export function connect(");
  });
});

describe("generateSchemaTs — payload-only json fields", () => {
  const jsonManifest: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      fields: {
        ...manifest.schema.fields,
        image_uris: { kind: "json", isDate: false, indexed: false, operators: [], pruning: [] },
      },
    },
  };
  const output = generateSchemaTs(jsonManifest, "0.1.0");

  test("a json field is an optional `unknown` in the record interface", () => {
    expect(output).toMatch(/image_uris\?:\s*unknown;/);
  });

  test("a json field never appears in the queryable schema descriptor", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).not.toContain("image_uris");
  });
});

describe("generateSchemaTs — tsType escape hatch for json payloads", () => {
  const typed: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      fields: {
        ...manifest.schema.fields,
        image_uris: {
          kind: "json",
          isDate: false,
          indexed: false,
          operators: [], pruning: [],
          tsType: "ImageUris",
          tsImport: 'import type { ImageUris } from "../types/scryfall.js";',
        },
        prices: {
          kind: "json",
          isDate: false,
          indexed: false,
          operators: [], pruning: [],
          tsType: "Record<string, string | null>",
        },
        // a second field importing from the same module must not duplicate the import
        card_faces: {
          kind: "json",
          isDate: false,
          indexed: false,
          operators: [], pruning: [],
          tsType: "CardFace[]",
          tsImport: 'import type { ImageUris } from "../types/scryfall.js";',
        },
      },
    },
  };
  const output = generateSchemaTs(typed, "0.1.0");

  test("uses the declared type instead of `unknown`", () => {
    expect(output).toMatch(/image_uris\?:\s*ImageUris;/);
    expect(output).not.toMatch(/image_uris\?:\s*unknown;/);
  });

  test("accepts an arbitrary type expression, not just a bare name", () => {
    expect(output).toMatch(/prices\?:\s*Record<string, string \| null>;/);
  });

  test("emits each distinct tsImport once, above the interface", () => {
    const importLine = 'import type { ImageUris } from "../types/scryfall.js";';
    expect(output.split(importLine)).toHaveLength(2); // exactly one occurrence
    expect(output.indexOf(importLine)).toBeLessThan(output.indexOf("export interface Movies"));
  });

  test("a tsType field stays optional — zonemapdb never tracks json presence, so it can't promise more", () => {
    expect(output).toMatch(/prices\?:/);
  });

  test("declaring a type does not make the field queryable", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    expect(schemaBlock).not.toContain("image_uris");
  });
});

describe("codegen — collection names that aren't valid identifiers", () => {
  const gnarly: Manifest = {
    ...manifest,
    dataset: { ...manifest.dataset, collection: "default-cards-20260721211623" },
    schema: { ...manifest.schema, collection: "default-cards-20260721211623" },
  };

  test("sanitizes the record type name to a valid PascalCase identifier", () => {
    const output = generateSchemaTs(gnarly, "0.1.0");
    expect(output).toContain("export interface DefaultCards20260721211623 {");
    expect(output).not.toMatch(/interface Default-cards/);
    expect(output).not.toMatch(/interface Default_cards/);
  });

  test("quotes the collection key everywhere it's used as an object/interface key", () => {
    const schema = generateSchemaTs(gnarly, "0.1.0");
    const client = generateClientTs(gnarly, { basePath: "/zonemapdb", generatorVersion: "0.1.0" });
    expect(schema).toContain('"default-cards-20260721211623": DefaultCards20260721211623;');
    expect(client).toContain('"default-cards-20260721211623": Collection<');
    // No bare (unquoted) hyphenated key survives — that would be a TS syntax error.
    expect(schema).not.toMatch(/\n\s*default-cards-20260721211623:/);
    expect(client).not.toMatch(/\n\s*default-cards-20260721211623:/);
  });
});

describe("generateSchemaTs — enum-like value unions", () => {
  const valued: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      fields: {
        ...manifest.schema.fields,
        certification: {
          kind: "string",
          isDate: false,
          indexed: true,
          operators: ["equals", "in", "startsWith"], pruning: ["equals", "in", "startsWith"],
          values: ["G", "PG", "R"],
        },
        genres: {
          kind: "string",
          isDate: false,
          indexed: true,
          operators: ["equals", "in", "startsWith"], pruning: ["equals", "in", "startsWith"],
          multi: true,
          values: ["Drama", "SciFi"],
        },
      },
    },
  };
  const output = generateSchemaTs(valued, "0.1.0");

  test("exports a named union per valued field, so app code can import it", () => {
    expect(output).toContain('export type MoviesCertification = "G" | "PG" | "R";');
    expect(output).toContain('export type MoviesGenres = "Drama" | "SciFi";');
  });

  test("carries the values into the schema descriptor, where the runtime narrows from", () => {
    expect(output).toContain('values: ["G", "PG", "R"]');
    expect(output).toContain('values: ["Drama", "SciFi"]');
  });

  test("leaves the RECORD field wide — a value outside the union is still valid data", () => {
    const recordBlock = output.slice(output.indexOf("export interface Movies {"), output.indexOf("export interface Records"));
    expect(recordBlock).toMatch(/certification:\s*string;/);
    expect(recordBlock).toMatch(/genres:\s*string\[\];/);
    expect(recordBlock).not.toContain('"PG"');
  });

  test("emits no union for a field without values", () => {
    expect(output).not.toContain("export type MoviesYear");
    expect(output).not.toContain("export type MoviesTitle");
  });

  test("a manifest with no valued fields emits no union block at all", () => {
    const plain = generateSchemaTs(manifest, "0.1.0");
    expect(plain).not.toContain("export type Movies" + "Year");
    expect(plain.split("\n")[1]).toBe("export interface Movies {");
  });

  test("sanitizes a field name that isn't a valid identifier into the union's type name", () => {
    const gnarly: Manifest = {
      ...manifest,
      schema: {
        ...manifest.schema,
        fields: {
          ...manifest.schema.fields,
          "border-color": {
            kind: "string",
            isDate: false,
            indexed: true,
            operators: ["equals"], pruning: ["equals"],
            values: ["black", "white"],
          },
        },
      },
    };
    const out = generateSchemaTs(gnarly, "0.1.0");
    expect(out).toContain('export type MoviesBorderColor = "black" | "white";');
    expect(out).toContain('"border-color": { kind: "string"');
  });
});

describe("generateSchemaTs — valuesType shares one union across fields", () => {
  const field = (values: string[], valuesType?: string) => ({
    kind: "string" as const, isDate: false, indexed: true,
    operators: ["equals", "in", "startsWith"], pruning: ["equals", "in", "startsWith"], values,
    ...(valuesType ? { valuesType } : {}),
  });
  const shared: Manifest = {
    ...manifest,
    schema: {
      ...manifest.schema,
      fields: {
        ...manifest.schema.fields,
        colors: field(["B", "G", "R", "U", "W"], "Color"),
        color_identity: field(["B", "G", "R", "U", "W"], "Color"),
        color_indicator: field(["B", "G", "R", "U", "W"], "Color"),
        // a genuinely different set, sharing nothing — proves it generalises past one name
        rarity: field(["common", "mythic", "rare"], "Rarity"),
        // and an undeclared field keeps its own per-field alias
        lang: field(["de", "en", "ja"]),
      },
    },
  };
  const output = generateSchemaTs(shared, "0.1.0");

  test("emits each shared union exactly once, under the declared name", () => {
    expect(output.split('export type Color = "B" | "G" | "R" | "U" | "W";')).toHaveLength(2);
    expect(output).toContain('export type Rarity = "common" | "mythic" | "rare";');
  });

  test("does not also emit per-field aliases for the fields that declared a name", () => {
    expect(output).not.toMatch(/MoviesColors\b/);
    expect(output).not.toMatch(/MoviesColor_identity\b/);
    expect(output).not.toMatch(/MoviesColor_indicator\b/);
  });

  test("leaves undeclared fields with their own alias", () => {
    expect(output).toMatch(/export type MoviesLang = "de" \| "en" \| "ja";/);
  });

  test("narrowing is unaffected — every field still carries its own values tuple", () => {
    const schemaBlock = output.slice(output.indexOf("export const schema"));
    for (const f of ["colors", "color_identity", "color_indicator", "rarity", "lang"]) {
      expect(schemaBlock).toContain(`${f}: { kind: "string"`);
    }
    expect(schemaBlock).toMatch(/colors: \{[^}]*values: \["B", "G", "R", "U", "W"\]/);
  });
});

describe("generateSchemaTs — generated type names are PascalCase", () => {
  const valued = (values: string[]) => ({
    kind: "string" as const, isDate: false, indexed: true, operators: ["equals", "in"], pruning: ["equals", "in"], values,
  });
  const withFields = (fields: Record<string, ReturnType<typeof valued>>): Manifest => ({
    ...manifest,
    schema: { ...manifest.schema, fields: { ...manifest.schema.fields, ...fields } },
  });

  test("snake_case, kebab-case and dotted field names all become PascalCase", () => {
    const output = generateSchemaTs(
      withFields({
        color_identity: valued(["B", "W"]),
        "frame-effects": valued(["etched"]),
        "set.name": valued(["Vintage Masters"]),
      }),
      "0.1.0",
    );
    expect(output).toContain("export type MoviesColorIdentity =");
    expect(output).toContain("export type MoviesFrameEffects =");
    expect(output).toContain("export type MoviesSetName =");
    // the old shape, which is not a name anyone wants
    expect(output).not.toMatch(/Movies[A-Za-z]*_[a-z]/);
  });

  test("a leading digit still gets prefixed so the name stays a valid identifier", () => {
    expect(generateSchemaTs(withFields({ "2fa_status": valued(["on"]) }), "0.1.0")).toContain("export type Movies_2faStatus =");
  });

  test("two field names that collapse to the same type name fail loudly instead of emitting duplicate exports", () => {
    // `_id` and `id`, or snake and camel spellings of one name, both mangle to one identifier — which
    // would generate a TS file that cannot compile. Fail with the remedy named.
    expect(() => generateSchemaTs(withFields({ color_identity: valued(["B"]), colorIdentity: valued(["B"]) }), "0.1.0")).toThrow(
      /MoviesColorIdentity[\s\S]*valuesType|valuesType[\s\S]*MoviesColorIdentity/,
    );
  });
});
