import type { Compression, FieldSchemaEntry, Manifest } from "./types.js";

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * A valid PascalCase TS type name from an arbitrary field or collection name: split on every
 * non-identifier run (the hyphens in a filename-derived `default-cards-2026`, the underscore in
 * `color_identity`, a dot in `set.name`), capitalize each segment, and prefix `_` if the result would
 * start with a digit. Previously only the first character was uppercased, which left snake_case intact
 * and produced names like `CardsColor_identity`.
 */
function typeNameFor(name: string): string {
  const segments = name.split(/[^A-Za-z0-9$]+/).filter((segment) => segment.length > 0);
  if (segments.length === 0) return "_";
  const pascal = segments.map((segment) => segment[0]!.toUpperCase() + segment.slice(1)).join("");
  return /^[0-9]/.test(pascal) ? `_${pascal}` : pascal;
}

/**
 * Guards the one hazard of mangling names down to identifiers: two distinct fields can collapse onto
 * the same type name (`_id` and `id`, or `color_identity` beside `colorIdentity`), which would emit
 * duplicate `export type` declarations and generate a file that cannot compile. Fail with the fix
 * named rather than writing broken output.
 */
function assertNoTypeNameCollisions(emitted: { name: string; source: string }[]): void {
  const byName = new Map<string, string[]>();
  for (const { name, source } of emitted) {
    const sources = byName.get(name);
    if (sources) sources.push(source);
    else byName.set(name, [source]);
  }
  for (const [name, sources] of byName) {
    if (sources.length < 2) continue;
    throw new Error(
      `zonedb: fields ${sources.map((s) => `"${s}"`).join(" and ")} both generate the type name ` +
        `"${name}", which would emit duplicate exports. Give one of them an explicit "valuesType" to ` +
        `separate them, or rename a field upstream.`,
    );
  }
}

/** An object/interface key: emitted bare when it's a valid identifier, otherwise quoted (`"a-b": …`). */
function propKey(name: string): string {
  return IDENTIFIER_RE.test(name) ? name : JSON.stringify(name);
}

function tsTypeForKind(kind: string): string {
  switch (kind) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
    case "date":
      return "string";
    case "json":
    default:
      return "unknown";
  }
}

/**
 * The distinct `tsImport` statements the emitted interface needs, in first-seen field order.
 * Deduplicated because several payload fields commonly draw their types from one module — emitting
 * the same import twice wouldn't compile.
 */
function payloadImportLines(fields: [string, FieldSchemaEntry][]): string {
  const seen = new Set<string>();
  for (const [, field] of fields) {
    if (field.tsType !== undefined && field.tsImport !== undefined) seen.add(field.tsImport);
  }
  return seen.size === 0 ? "" : `${[...seen].join("\n")}\n\n`;
}

function generatedHeader(generatorVersion: string): string {
  return `// generated by zonedb@${generatorVersion} — do not edit`;
}

export function generateSchemaTs(manifest: Manifest, generatorVersion: string): string {
  const { collection, fields } = manifest.schema;
  const typeName = typeNameFor(collection);
  const collectionKey = propKey(collection);
  const fieldEntries = Object.entries(fields);

  const interfaceLines = fieldEntries
    .map(([name, field]) => {
      // A configured `tsType` replaces the opaque `unknown` a payload field would otherwise get. It
      // is never validated against the data — the config asserts it, zonedb just relays it.
      const base = field.tsType ?? tsTypeForKind(field.kind);
      const listOrScalar = field.multi ? `${base}[]` : base;
      // `unknown` already includes null, so only a concrete type needs `| null` spelled out.
      const tsType = field.nullable && listOrScalar !== "unknown" ? `${listOrScalar} | null` : listOrScalar;
      // Payload-only "json" fields are opaque and their presence isn't tracked — always optional,
      // declared type or not: zonedb can't promise a key exists when it never checked.
      const optional = field.absent || field.kind === "json" ? "?" : "";
      return `  ${propKey(name)}${optional}: ${tsType};`;
    })
    .join("\n");

  // Every queryable field, indexed or not: an unindexed field is filterable too, its filters just
  // don't prune (ADR-0013). `pruning` is what the runtime's rider guard reads.
  const queryableFieldLines = fieldEntries
    .filter(([, field]) => field.operators.length > 0)
    .map(([name, field]) => {
      const operators = field.operators.map((op) => `"${op}"`).join(", ");
      const pruning = field.pruning.map((op) => `"${op}"`).join(", ");
      const multi = field.multi ? ", multi: true" : "";
      const absent = field.absent ? ", absent: true" : "";
      const nullable = field.nullable ? ", nullable: true" : "";
      const pk = field.pk ? ", pk: true" : "";
      // The runtime reads this tuple to narrow equals/in/some to the field's value union.
      const values = field.values ? `, values: [${field.values.map((v) => JSON.stringify(v)).join(", ")}]` : "";
      return `      ${propKey(name)}: { kind: "${field.kind}", operators: [${operators}], pruning: [${pruning}]${multi}${absent}${nullable}${pk}${values} },`;
    })
    .join("\n");

  const pkLine = manifest.schema.pk !== undefined ? `    pk: ${JSON.stringify(manifest.schema.pk)},\n` : "";

  /**
   * A named union per enum-like field, exported so app code can use it directly (a filter component's
   * prop, a dropdown's options) instead of hand-rolling the same literal union. The record interface
   * deliberately keeps these fields as plain `string` — see `tsTypeForKind`.
   *
   * Fields that declare a `valuesType` share ONE emitted type under that name instead of each getting
   * a near-duplicate alias, and the per-field alias is not emitted for them: the name they asked for is
   * the name they get. Narrowing is unaffected either way — `where` reads the `values` tuple in the
   * schema const below, not these aliases.
   */
  const valued = fieldEntries.filter(([, field]) => field.operators.length > 0 && field.values !== undefined);
  const unionOf = (values: readonly string[]): string => values.map((v) => JSON.stringify(v)).join(" | ");

  const sharedNames: string[] = [];
  const sharedUnions = new Map<string, string>();
  for (const [, field] of valued) {
    if (field.valuesType === undefined || sharedUnions.has(field.valuesType)) continue;
    sharedUnions.set(field.valuesType, unionOf(field.values!));
    sharedNames.push(field.valuesType);
  }

  const perField = valued
    .filter(([, field]) => field.valuesType === undefined)
    .map(([name, field]) => ({ name: `${typeName}${typeNameFor(name)}`, source: name, union: unionOf(field.values!) }));
  assertNoTypeNameCollisions([
    ...sharedNames.map((name) => ({ name, source: `valuesType "${name}"` })),
    ...perField,
  ]);

  const valueUnions = [
    ...sharedNames.map((name) => `export type ${name} = ${sharedUnions.get(name)!};`),
    ...perField.map((entry) => `export type ${entry.name} = ${entry.union};`),
  ].join("\n");
  const valueUnionBlock = valueUnions ? `${valueUnions}\n\n` : "";

  return `${generatedHeader(generatorVersion)}
${payloadImportLines(fieldEntries)}${valueUnionBlock}export interface ${typeName} {
${interfaceLines}
}

export interface Records {
  ${collectionKey}: ${typeName};
}

export const schema = {
  ${collectionKey}: {
${pkLine}    fields: {
${queryableFieldLines}
    },
  },
} as const;

export type Schema = typeof schema;
`;
}

export function generateClientTs(
  manifest: Manifest,
  opts: { basePath: string; generatorVersion: string; manifestCompression?: Compression },
): string {
  const { collection } = manifest.schema;
  const collectionKey = propKey(collection);
  const collectionIndex = JSON.stringify(collection);

  return `${generatedHeader(opts.generatorVersion)}
import { createClient, type Collection, type ClientOptions, type GenericClient } from "zonedb";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  ${collectionKey}: Collection<Schema[${collectionIndex}], Records[${collectionIndex}]>;
}

const DEFAULT_BASE_PATH = ${JSON.stringify(opts.basePath)};
${
  opts.manifestCompression
    ? `// This build pre-compressed the manifest. Everything else the manifest points at carries its
// encoding in its own path, but the manifest is fetched before any of that can be read — so it is
// stamped here, by the same build that wrote the file.
const MANIFEST_COMPRESSION = ${JSON.stringify(opts.manifestCompression)} as const;
`
    : ""
}
export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
${opts.manifestCompression ? "    manifestCompression: MANIFEST_COMPRESSION,\n" : ""}    ...opts,
  });
  return generic as unknown as Db;
}
`;
}
